import Navigation from "@/components/Navigation";
import "./globals.scss";
import type { Metadata } from "next";
import Head from "next/head";
import Footer from "@/components/Footer";
import { DarkModeProvider } from "@/contexts/DarkModeContext";

export const metadata: Metadata = {
    title: "Pann's Website",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <DarkModeProvider>
            <html lang="en" className="dark-mode">
                <body>
                    <Navigation />
                    {children}
                    <Footer />
                </body>
            </html>
        </DarkModeProvider>
    );
}
